# Estruturas de Dados
## Tópicos:
1. Tuplas;
2. Dicionários;
3. Arrays;
4. Matriz.

**Observação:** dicionários e arrays são mutáveis, mas tuplas não é.

## Tuplas

In [7]:
animais = ("cobras", "gatos", "morcegos")

animais[1];     # elemento da primeira posição

In [8]:
coisa = (cor = "azul", numero = 10, letra = 'b')

coisa[1]       # elemento associado ao primeiro elemento
coisa.numero;   # elemento associado à numero

## Dicionários

In [ ]:
contatos = Dict("Jenny" => "867-5309", "Ghostbusters" => "555-2368")

contatos["Jenny"]               # elemento associado à Jenny
contatos["Kramer"] = "555-FILK" # adicionar novo contato
pop!(contatos, "Jenny")         # remover contato

## Array

In [ ]:
amigos = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]

amigos[3]                    # elemento da terceira posição
amigos[1:3]                  # elementos da primeira, segunda e terceira posição
quadrado[end]                # elemento da última posição
amigos[3] = "Baby Bop"       # altera elemento da terceira posição
push!(amigos, "Julia")       # adiciona novo elemento no final
pop!(amigos)                 # exclui ultimo elemento
popfirst!(amigos)            # exclui primeiro elemento
pushfirst!(amigos, "Julia")  # adiciona novo elemento no início
amigos2 = copy(amigos)       # copia
typeof(amigos)               # retorna o tipo

In [1]:
mistura = [1, 1.4, "Ted", 'a', true]

5-element Array{Any,1}:
    1
    1.4
     "Ted"
     'a'
 true

In [50]:
A = rand(0:10, 5) # array com 5 elementos inteiros aleatórios entre 0 e 10

5-element Array{Int64,1}:
  4
  1
  7
  3
 10

In [51]:
sort(A) # retorna A ordenado, mas não altera

5-element Array{Int64,1}:
  1
  3
  4
  7
 10

In [52]:
A

5-element Array{Int64,1}:
  4
  1
  7
  3
 10

In [53]:
sort!(A) # ordena e altera A

5-element Array{Int64,1}:
  1
  3
  4
  7
 10

In [54]:
A

5-element Array{Int64,1}:
  1
  3
  4
  7
 10

In [75]:
cubo = [i^3 for i in 1:8]

8-element Array{Int64,1}:
   1
   8
  27
  64
 125
 216
 343
 512

In [62]:
numeros = [[1,2,3],[4,5],[6,7,8,9]]

3-element Array{Array{Int64,1},1}:
 [1, 2, 3]
 [4, 5]
 [6, 7, 8, 9]

In [88]:
numeros[1] # elementos do primeiro array

3-element Array{Int64,1}:
 1
 2
 3

In [89]:
numeros[2][1] # primeiro elemento do segundo array

4

In [95]:
[1, 2.3, 4//5] # quando os elementos são números de tipos diferentes, todos os valores serão convertidos para o mesmo tipo que o valor do tipo "mais alto"

3-element Array{Float64,1}:
 1.0
 2.3
 0.8

In [100]:
[1:2; 4:6]

5-element Array{Int64,1}:
 1
 2
 4
 5
 6

## Matriz

In [63]:
rand(4, 3) # Matriz aleatório com 4 linhas e 3 colunas

4×3 Array{Float64,2}:
 0.880088  0.916076  0.144635
 0.901728  0.977608  0.711985
 0.584023  0.845384  0.367259
 0.710864  0.502877  0.135766

In [64]:
rand(4, 3, 2) # 2 Matrizes aleatórias com 4 linhas e 3 colunas

4×3×2 Array{Float64,3}:
[:, :, 1] =
 0.754197  0.708239  0.577198
 0.428898  0.963052  0.750444
 0.221209  0.816905  0.823675
 0.956143  0.913457  0.251092

[:, :, 2] =
 0.311901  0.30666   0.9725
 0.743963  0.950265  0.66107
 0.93139   0.435572  0.951012
 0.326782  0.57498   0.426366

In [65]:
fill(1, (3, 3)) # matriz de 1 com 3 linhas e 3 colunas

3×3 Array{Int64,2}:
 1  1  1
 1  1  1
 1  1  1

In [66]:
fill(0, (5, 5)) # matriz de zero com 5 linhas e 5 colunas

5×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0
 0  0  0  0  0

In [67]:
# ou

zeros(5, 5)

5×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [68]:
zeros((2, 3))

2×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0

In [69]:
zeros(Int8, (2, 3))

2×3 Array{Int8,2}:
 0  0  0
 0  0  0

In [70]:
A = fill(0, (5, 5))

for i in 1:5
    for j in 1:5
        A[i, j] = i + j
    end
end

A

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [71]:
# ou

B = fill(0, (5, 5))

for i in 1:5, j in 1:5
    B[i, j] = i + j
end

B

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [72]:
# ou 

C = fill(0, (5, 5))

C = [i + j for i in 1:5, j in 1:5]

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [ ]:
C[1]    # primeiro elemento da matriz
C[25]   # 25º elemento da matriz
C[2,2]  # elemento da segunda linha e segunda coluna

In [106]:
[1:2  4:5]

2×2 Array{Int64,2}:
 1  4
 2  5

In [108]:
[1 2 3]

1×3 Array{Int64,2}:
 1  2  3

In [109]:
[1 2
 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [111]:
K = [1 6
     3 7]

for i in eachindex(K) # índice
    println(i)
end

1
2
3
4
